name: CI CD Workflow Testing
on: [push]
jobs:
  BlazeDemo_cypress_cross_browser_testing:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cypress.io
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Users/Benjamin/Documents/BlazeDemo_Automate_Updated_4/cypress
          start: npm run cypress:open:electron